# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51e4c39d1f6e674bc3f24f297d673887cdd4da8e9e2f195578ecfaa7b640adfe0fb24599f7bbb9bdeb1195fa4f93afd507d6ed86aa6fe65a7ccce2a2c68800de

test:
  secret_key_base: 2f0890312a785e66729df8de305ebbadfcc8ff6a570478cc2b27289121ce9f6513ac3d9445a6efc351312404fc7fda341ee7e6ee5859d3895041d8e0798e0692

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
